export type Layer2Type =
  | 'flow'
  | 'smoke'
  | 'liquid'
  | 'wind'
  | 'gravity'
  | 'explosion'
  | 'linear'
  | 'field'
  | 'morph'
  | 'attractor'
  | 'swirl'
  | 'wave'
  | 'curl'
  | 'noise'
  | 'euler'
  | 'lorenz'
  | 'aizawa'
  | 'rossler'
  | 'thomas'
  | 'spring'
  | 'vortex'
  | 'aero'
  | 'aux'
  | 'orbit'
  | 'spiral_motion'
  | 'helix'
  | 'uniform'
  | 'gaussian'
  | 'brownian'
  | 'phyllotaxis'
  | 'rose_curve'
  | 'ridged_mf'
  | 'lissajous'
  | 'toroidal'
  | 'pendulum'
  | 'lattice'
  | 'epicycle'
  | 'gyre'
  | 'crystal'
  | 'ripple_ring'
  | 'fold'
  | 'kaleidoscope'
  | 'braid'
  | 'arc_wave'
  | 'web'
  | 'pulse_shell'
  | 'mandala'
  | 'ribbon'
  | 'shear'
  | 'spokes'
  | 'breathing'
  | 'torus_knot'
  | 'clifford'
  | 'hopalong'
  | 'cellular'
  | 'cyclone'
  | 'petals'
  | 'sheet'
  | 'flare'
  | 'moebius'
  | 'harmonic'
  | 'starburst'
  | 'grid_wave'
  | 'helio'
  | 'zigzag'
  | 'shockwave'
  | 'filament'
  | 'mirror_fold'
  | 'radial_steps'
  | 'coil'
  | 'labyrinth'
  | 'gyro'
  | 'echo_ring'
  | 'braidshell'
  | 'crosscurrent'
  | 'prism'
  | 'tessellate'
  | 'pulse_grid'
  | 'tidal'
  | 'beacon'
  | 'caustic'
  | 'pinwheel'
  | 'nebula'
  | 'fronds'
  | 'gyroflower'
  | 'monolith'
  | 'runes'
  | 'fanout'
  | 'eddy'
  | 'nova';

export type Layer3Source =
  | 'sphere'
  | 'center'
  | 'ring'
  | 'disc'
  | 'cube'
  | 'cylinder'
  | 'random'
  | 'cone'
  | 'torus'
  | 'spiral'
  | 'galaxy'
  | 'grid'
  | 'plane';

export type InterLayerCollisionMode = 'layer-volume' | 'source-volume';

export type ParticleTone = 'white' | 'black';

export type BackgroundTone = 'black' | 'white';
export type CameraControlMode = 'auto' | 'hybrid' | 'manual';
export type RenderQuality = 'draft' | 'balanced' | 'cinematic';

export type ParticleSpriteMode = 'soft' | 'ring' | 'spark';
export type ParticleBurstMode = 'radial' | 'cone' | 'sweep';
export type ParticleBurstWaveform = 'single' | 'loop' | 'stutter' | 'heartbeat';

export type Position3D = { x: number; y: number; z: number };
