import type { ParticleConfig, PresetLibraryData, PresetRecord, PresetSequenceItem } from '../types';
import { DEFAULT_CONFIG, normalizeConfig } from './appStateConfig';

const STARTER_TIMESTAMP = '2026-03-14T00:00:00.000Z';

function optimizeStarterConfig(config: Partial<ParticleConfig>): Partial<ParticleConfig> {
  const next = { ...config };
  next.layer1Count = Math.min(next.layer1Count ?? DEFAULT_CONFIG.layer1Count, 9000);
  next.layer2Count = Math.min(next.layer2Count ?? DEFAULT_CONFIG.layer2Count, 14000);
  next.layer3Count = Math.min(next.layer3Count ?? DEFAULT_CONFIG.layer3Count, 4500);
  next.ambientCount = Math.min(next.ambientCount ?? DEFAULT_CONFIG.ambientCount, 1500);
  next.layer2AuxCount = Math.min(next.layer2AuxCount ?? DEFAULT_CONFIG.layer2AuxCount, 2800);
  next.layer3AuxCount = Math.min(next.layer3AuxCount ?? DEFAULT_CONFIG.layer3AuxCount, 1600);
  next.layer2SparkCount = Math.min(next.layer2SparkCount ?? DEFAULT_CONFIG.layer2SparkCount, 2600);
  next.layer3SparkCount = Math.min(next.layer3SparkCount ?? DEFAULT_CONFIG.layer3SparkCount, 1400);
  next.layer2Fidelity = Math.min(next.layer2Fidelity ?? DEFAULT_CONFIG.layer2Fidelity, 2);
  next.layer3Fidelity = Math.min(next.layer3Fidelity ?? DEFAULT_CONFIG.layer3Fidelity, 2);
  next.screenPersistenceIntensity = Math.min(next.screenPersistenceIntensity ?? DEFAULT_CONFIG.screenPersistenceIntensity, 0.12);
  next.screenPersistenceLayers = Math.min(next.screenPersistenceLayers ?? DEFAULT_CONFIG.screenPersistenceLayers, 2);
  next.screenInterferenceIntensity = Math.min(next.screenInterferenceIntensity ?? DEFAULT_CONFIG.screenInterferenceIntensity, 0.12);
  next.screenNoiseIntensity = Math.min(next.screenNoiseIntensity ?? DEFAULT_CONFIG.screenNoiseIntensity, 0.14);

  if ((next.layer2Count ?? 0) > 16000 && next.renderQuality === 'cinematic') {
    next.renderQuality = 'balanced';
  }
  if ((next.layer2Count ?? 0) > 16000) {
    next.layer2ConnectionOpacity = Math.min(next.layer2ConnectionOpacity ?? DEFAULT_CONFIG.layer2ConnectionOpacity, 0.14);
  }
  if ((next.layer3Count ?? 0) > 6000) {
    next.layer3ConnectionOpacity = Math.min(next.layer3ConnectionOpacity ?? DEFAULT_CONFIG.layer3ConnectionOpacity, 0.14);
  }

  return next;
}

function createStarterPreset(
  id: string,
  name: string,
  config: Partial<ParticleConfig>,
): PresetRecord {
  return {
    id,
    name,
    config: normalizeConfig({ ...DEFAULT_CONFIG, ...optimizeStarterConfig(config) }),
    createdAt: STARTER_TIMESTAMP,
    updatedAt: STARTER_TIMESTAMP,
  };
}

export const STARTER_PRESETS: PresetRecord[] = [
  createStarterPreset('starter-simple-clean', 'Starter Clean', {
    cameraControlMode: 'hybrid',
    renderQuality: 'balanced',
    cameraDistance: 60,
    opacity: 0.85,
    contrast: 1.0,
    particleSoftness: 0.5,
    particleGlow: 0.2,
    rotationSpeedX: 0.0005,
    rotationSpeedY: 0.001,
    layer1Enabled: true,
    layer1Count: 2000,
    baseSize: 1.0,
    sphereRadius: 50,
    layer1Volume: 0.0,
    jitter: 0.0,
    pulseSpeed: 0.003,
    pulseAmplitude: 0.5,
    layer2Enabled: false,
    layer2Type: 'flow',
    layer2Source: 'sphere',
    layer2Count: 3000,
    layer2BaseSize: 0.8,
    layer2RadiusScale: 1.0,
    layer2FlowAmplitude: 20,
    layer2FlowFrequency: 1.5,
    layer2Trail: 0,
    layer2NoiseScale: 1.0,
    layer2FluidForce: 1.0,
    layer2Life: 0,
    layer2LifeSpread: 0,
    layer2Burst: 0,
    layer2Streak: 0,
    layer2Fidelity: 1,
    layer2ConnectionEnabled: false,
    layer2AuxEnabled: false,
    layer2SparkEnabled: false,
    layer3Enabled: false,
    ambientEnabled: false,
    ambientCount: 0,
    ambientBaseSize: 0.5,
    screenPersistenceIntensity: 0,
    screenNoiseIntensity: 0,
    screenInterferenceIntensity: 0,
    screenPulseIntensity: 0,
    screenBurstDrive: 0,
    depthFogEnabled: false,
  }),
  createStarterPreset('starter-fluid-curl', 'Fluid Curl Field', {
    cameraControlMode: 'hybrid',
    renderQuality: 'balanced',
    layer1Count: 18000,
    layer2Type: 'curl',
    layer2Count: 28000,
    layer2FlowAmplitude: 62,
    layer2FlowFrequency: 2.6,
    layer2Trail: 0.62,
    layer2NoiseScale: 1.25,
    layer2FluidForce: 1.4,
    layer3Enabled: true,
    layer3Type: 'smoke',
    layer3Count: 9000,
    layer3BaseSize: 0.75,
    screenPersistenceIntensity: 0.08,
  }),
  createStarterPreset('starter-chaos-lorenz', 'Chaos Lorenz Bloom', {
    cameraControlMode: 'auto',
    renderQuality: 'cinematic',
    layer1Count: 14000,
    layer2Type: 'lorenz',
    layer2Count: 32000,
    layer2FlowAmplitude: 84,
    layer2Complexity: 3.4,
    layer2Trail: 0.3,
    layer3Enabled: true,
    layer3Type: 'thomas',
    layer3Count: 12000,
    layer3FlowAmplitude: 68,
    layer3Trail: 0.52,
    screenPulseIntensity: 0.14,
    depthFogEnabled: true,
  }),
  createStarterPreset('starter-orbital-epicycle', 'Orbital Epicycle', {
    layer1Count: 12000,
    baseSize: 1.2,
    sphereRadius: 150,
    layer2Type: 'epicycle',
    layer2Count: 26000,
    layer2Source: 'ring',
    layer2FlowAmplitude: 58,
    layer2ConnectionEnabled: true,
    layer2ConnectionDistance: 34,
    layer2ConnectionOpacity: 0.18,
    layer3Enabled: true,
    layer3Type: 'orbit',
    layer3Count: 6000,
    layer3Source: 'torus',
    layer3BaseSize: 0.72,
  }),
  createStarterPreset('starter-geometry-lattice', 'Geometry Lattice', {
    viewMode: 'orthographic',
    cameraControlMode: 'manual',
    renderQuality: 'balanced',
    layer1Count: 16000,
    layer2Type: 'lattice',
    layer2Source: 'grid',
    layer2Count: 24000,
    layer2FlowAmplitude: 42,
    layer2ConnectionEnabled: true,
    layer2ConnectionDistance: 26,
    layer2ConnectionOpacity: 0.22,
    layer3Enabled: true,
    layer3Type: 'crystal',
    layer3Source: 'cube',
    layer3Count: 7000,
    screenScanlineIntensity: 0.12,
  }),
  createStarterPreset('starter-ripple-broadcast', 'Ripple Broadcast', {
    layer2Type: 'ripple_ring',
    layer2Source: 'disc',
    layer2Count: 22000,
    layer2FlowAmplitude: 74,
    layer2FlowFrequency: 4.2,
    screenScanlineIntensity: 0.38,
    screenScanlineDensity: 640,
    screenNoiseIntensity: 0.12,
    screenInterferenceIntensity: 0.16,
    screenSweepIntensity: 0.18,
    screenSequenceDriveEnabled: true,
    screenSequenceDriveStrength: 0.22,
  }),
  createStarterPreset('starter-pendulum-noir', 'Pendulum Noir', {
    particleColor: 'black',
    backgroundColor: 'white',
    layer1Count: 11000,
    layer2Type: 'pendulum',
    layer2Count: 18000,
    layer2FlowAmplitude: 52,
    layer2Trail: 0.44,
    layer3Enabled: true,
    layer3Type: 'fold',
    layer3Count: 8000,
    layer3BaseSize: 0.42,
    contrast: 1.35,
    particleSoftness: 0.2,
  }),
  createStarterPreset('starter-toroidal-gyre', 'Toroidal Gyre', {
    layer1Count: 13000,
    layer2Type: 'toroidal',
    layer2Source: 'torus',
    layer2Count: 30000,
    layer2FlowAmplitude: 66,
    layer2Trail: 0.66,
    layer3Enabled: true,
    layer3Type: 'gyre',
    layer3Count: 10000,
    layer3FlowAmplitude: 58,
    layer3Trail: 0.46,
    ambientCount: 4500,
  }),
  createStarterPreset('starter-symmetry-lissajous', 'Symmetry Lissajous', {
    layer1Count: 10000,
    layer2Type: 'lissajous',
    layer2Source: 'sphere',
    layer2Count: 21000,
    layer2FlowAmplitude: 60,
    layer2FlowFrequency: 3.8,
    layer3Enabled: true,
    layer3Type: 'rose_curve',
    layer3Count: 9000,
    layer3FlowAmplitude: 40,
    screenVignetteIntensity: 0.1,
    screenPersistenceIntensity: 0.1,
  }),
  createStarterPreset('starter-aizawa-ink', 'Aizawa Ink Spiral', {
    particleColor: 'black',
    backgroundColor: 'white',
    contrast: 1.45,
    particleSoftness: 0.12,
    layer1Count: 9000,
    layer2Type: 'aizawa',
    layer2Count: 26000,
    layer2FlowAmplitude: 88,
    layer2Complexity: 3.8,
    layer2Trail: 0.34,
    layer3Enabled: true,
    layer3Type: 'helix',
    layer3Count: 7000,
    layer3FlowAmplitude: 34,
  }),
  createStarterPreset('starter-fractal-ridged', 'Fractal Ridged Storm', {
    layer1Count: 15000,
    layer2Type: 'ridged_mf',
    layer2Count: 31000,
    layer2FlowAmplitude: 78,
    layer2NoiseScale: 1.5,
    layer2OctaveMult: 2.6,
    layer2Fidelity: 4,
    layer2Trail: 0.58,
    layer3Enabled: true,
    layer3Type: 'noise',
    layer3Count: 9000,
    layer3FlowAmplitude: 46,
    screenInterferenceIntensity: 0.08,
  }),
  createStarterPreset('starter-brownian-veil', 'Brownian Veil', {
    layer1Count: 8000,
    layer2Type: 'brownian',
    layer2Source: 'plane',
    layer2Count: 19000,
    layer2FlowAmplitude: 44,
    layer2Trail: 0.2,
    layer3Enabled: true,
    layer3Type: 'smoke',
    layer3Count: 14000,
    layer3BaseSize: 0.92,
    layer3Trail: 0.18,
    ambientCount: 6500,
    screenPersistenceIntensity: 0.18,
    screenPersistenceLayers: 4,
  }),
  createStarterPreset('starter-wave-shell', 'Wave Shell', {
    layer1Count: 11000,
    layer2Type: 'wave',
    layer2Source: 'spiral',
    layer2Count: 23000,
    layer2FlowAmplitude: 56,
    layer2FlowFrequency: 4.6,
    layer2Trail: 0.48,
    layer3Enabled: true,
    layer3Type: 'spiral_motion',
    layer3Source: 'spiral',
    layer3Count: 6000,
    layer3FlowAmplitude: 36,
    screenSweepIntensity: 0.14,
    screenVignetteIntensity: 0.08,
  }),
  createStarterPreset('starter-kaleido-prism', 'Kaleido Prism', {
    layer1Count: 12000,
    layer2Type: 'kaleidoscope',
    layer2Source: 'cone',
    layer2Count: 24000,
    layer2FlowAmplitude: 54,
    layer2ConnectionEnabled: true,
    layer2ConnectionDistance: 30,
    layer2ConnectionOpacity: 0.16,
    layer3Enabled: true,
    layer3Type: 'crystal',
    layer3Source: 'cube',
    layer3Count: 8000,
    screenSplitIntensity: 0.12,
  }),
  createStarterPreset('starter-braid-web', 'Braid Web', {
    layer1Count: 10000,
    layer2Type: 'braid',
    layer2Source: 'cylinder',
    layer2Count: 22000,
    layer2FlowAmplitude: 48,
    layer2Trail: 0.36,
    layer3Enabled: true,
    layer3Type: 'web',
    layer3Source: 'grid',
    layer3Count: 11000,
    layer3FlowAmplitude: 30,
    layer3ConnectionEnabled: true,
    layer3ConnectionDistance: 24,
    layer3ConnectionOpacity: 0.18,
  }),
  createStarterPreset('starter-arcwave-halo', 'Arc Wave Halo', {
    layer1Count: 9000,
    layer2Type: 'arc_wave',
    layer2Source: 'disc',
    layer2Count: 21000,
    layer2FlowAmplitude: 58,
    layer2FlowFrequency: 4.8,
    layer3Enabled: true,
    layer3Type: 'wave',
    layer3Count: 7000,
    layer3FlowAmplitude: 42,
    screenPulseIntensity: 0.18,
    screenVignetteIntensity: 0.12,
  }),
  createStarterPreset('starter-pulse-shell', 'Pulse Shell', {
    cameraControlMode: 'auto',
    renderQuality: 'cinematic',
    cameraImpulseStrength: 0.24,
    cameraImpulseSpeed: 1.45,
    cameraImpulseDrift: 0.32,
    cameraBurstBoost: 0.68,
    screenBurstDrive: 0.54,
    screenBurstNoiseBoost: 0.42,
    screenBurstFlashBoost: 0.5,
    layer1Count: 11000,
    layer2Type: 'pulse_shell',
    layer2Source: 'galaxy',
    layer2Count: 26000,
    layer2FlowAmplitude: 72,
    layer2Trail: 0.54,
    layer2Life: 64,
    layer2LifeSpread: 0.28,
    layer2LifeSizeBoost: 0.62,
    layer2LifeSizeTaper: 0.34,
    layer2Burst: 0.72,
    layer2BurstMode: 'sweep',
    layer2BurstWaveform: 'stutter',
    layer2BurstSweepSpeed: 2.1,
    layer2BurstSweepTilt: 0.42,
    layer2EmitterOrbitSpeed: 1.4,
    layer2EmitterOrbitRadius: 36,
    layer2EmitterPulseAmount: 0.18,
    layer2TrailDrag: 0.62,
    layer2TrailTurbulence: 0.48,
    layer2TrailDrift: 0.34,
    layer2VelocityGlow: 0.95,
    layer2VelocityAlpha: 0.52,
    layer2FlickerAmount: 0.34,
    layer2FlickerSpeed: 3.4,
    layer2Streak: 1.2,
    layer2SpriteMode: 'spark',
    layer2SparkEnabled: true,
    layer2SparkCount: 12000,
    layer2SparkLife: 18,
    layer2SparkDiffusion: 3.4,
    layer2SparkBurst: 1.35,
    layer2LineVelocityGlow: 0.92,
    layer2LineVelocityAlpha: 0.54,
    layer2LineBurstPulse: 0.78,
    layer2LineShimmer: 0.32,
    layer2LineFlickerSpeed: 2.9,
    layer3Enabled: true,
    layer3Type: 'orbit',
    layer3Source: 'ring',
    layer3Count: 6000,
    layer3FlowAmplitude: 38,
    layer3Life: 90,
    layer3Burst: 0.35,
    layer3SpriteMode: 'ring',
    screenPersistenceIntensity: 0.12,
    screenSweepIntensity: 0.16,
  }),
  createStarterPreset('starter-mandala-bloom', 'Mandala Bloom', {
    layer1Count: 9000,
    layer2Type: 'mandala',
    layer2Source: 'disc',
    layer2Count: 24000,
    layer2FlowAmplitude: 64,
    layer2FlowFrequency: 4.4,
    layer3Enabled: true,
    layer3Type: 'rose_curve',
    layer3Count: 8000,
    layer3FlowAmplitude: 34,
    screenPulseIntensity: 0.16,
  }),
  createStarterPreset('starter-ribbon-shear', 'Ribbon Shear', {
    layer1Count: 10000,
    layer2Type: 'ribbon',
    layer2Source: 'cylinder',
    layer2Count: 22000,
    layer2FlowAmplitude: 52,
    layer2Trail: 0.42,
    layer3Enabled: true,
    layer3Type: 'shear',
    layer3Count: 10000,
    layer3FlowAmplitude: 36,
    layer3Trail: 0.22,
  }),
  createStarterPreset('starter-spokes-breath', 'Spokes Breath', {
    layer1Count: 11000,
    layer2Type: 'spokes',
    layer2Source: 'sphere',
    layer2Count: 25000,
    layer2FlowAmplitude: 58,
    layer2ConnectionEnabled: true,
    layer2ConnectionDistance: 28,
    layer2ConnectionOpacity: 0.16,
    layer3Enabled: true,
    layer3Type: 'breathing',
    layer3Count: 7000,
    layer3FlowAmplitude: 30,
    screenPersistenceIntensity: 0.1,
  }),
  createStarterPreset('starter-knot-flare', 'Torus Knot Flare', {
    layer1Count: 10000,
    layer2Type: 'torus_knot',
    layer2Source: 'torus',
    layer2Count: 24000,
    layer2FlowAmplitude: 62,
    layer2Trail: 0.5,
    layer3Enabled: true,
    layer3Type: 'flare',
    layer3Count: 7000,
    layer3FlowAmplitude: 28,
    screenSweepIntensity: 0.18,
  }),
  createStarterPreset('starter-cellular-sheet', 'Cellular Sheet', {
    viewMode: 'orthographic',
    layer1Count: 8000,
    layer2Type: 'cellular',
    layer2Source: 'grid',
    layer2Count: 22000,
    layer2FlowAmplitude: 40,
    layer3Enabled: true,
    layer3Type: 'sheet',
    layer3Source: 'plane',
    layer3Count: 9000,
    layer3FlowAmplitude: 30,
    screenScanlineIntensity: 0.1,
  }),
  createStarterPreset('starter-mirror-starburst', 'Mirror Starburst', {
    particleColor: 'black',
    backgroundColor: 'white',
    contrast: 1.4,
    layer1Count: 9000,
    layer2Type: 'starburst',
    layer2Source: 'sphere',
    layer2Count: 26000,
    layer2FlowAmplitude: 70,
    layer3Enabled: true,
    layer3Type: 'mirror_fold',
    layer3Count: 8000,
    layer3FlowAmplitude: 30,
  }),
  createStarterPreset('starter-cyclone-gridwave', 'Cyclone GridWave', {
    layer1Count: 10000,
    layer2Type: 'cyclone',
    layer2Source: 'cylinder',
    layer2Count: 24000,
    layer2FlowAmplitude: 60,
    layer2Trail: 0.44,
    layer3Enabled: true,
    layer3Type: 'grid_wave',
    layer3Source: 'grid',
    layer3Count: 9000,
    layer3FlowAmplitude: 34,
  }),
  createStarterPreset('starter-caustic-nebula', 'Caustic Nebula', {
    cameraControlMode: 'hybrid',
    renderQuality: 'cinematic',
    cameraImpulseStrength: 0.14,
    cameraImpulseSpeed: 0.9,
    cameraImpulseDrift: 0.18,
    cameraBurstBoost: 0.44,
    screenBurstDrive: 0.36,
    screenBurstNoiseBoost: 0.68,
    screenBurstFlashBoost: 0.24,
    layer1Count: 12000,
    layer2Type: 'caustic',
    layer2Source: 'disc',
    layer2Count: 26000,
    layer2FlowAmplitude: 64,
    layer2FlowFrequency: 4.4,
    layer2Trail: 0.48,
    layer2Life: 70,
    layer2LifeSpread: 0.42,
    layer2LifeSizeBoost: 0.36,
    layer2LifeSizeTaper: 0.22,
    layer2Burst: 0.6,
    layer2BurstMode: 'cone',
    layer2BurstWaveform: 'loop',
    layer2BurstConeWidth: 0.72,
    layer2EmitterOrbitSpeed: 0.65,
    layer2EmitterPulseAmount: 0.22,
    layer2TrailDrag: 0.38,
    layer2TrailTurbulence: 0.55,
    layer2TrailDrift: 0.18,
    layer2VelocityGlow: 0.72,
    layer2VelocityAlpha: 0.28,
    layer2FlickerAmount: 0.2,
    layer2FlickerSpeed: 1.9,
    layer2Streak: 0.9,
    layer2SpriteMode: 'spark',
    layer2SparkEnabled: true,
    layer2SparkCount: 9000,
    layer2SparkLife: 22,
    layer2SparkDiffusion: 2.8,
    layer2SparkBurst: 1.1,
    layer2LineVelocityGlow: 0.46,
    layer2LineVelocityAlpha: 0.3,
    layer2LineBurstPulse: 0.42,
    layer2LineShimmer: 0.18,
    layer2LineFlickerSpeed: 1.5,
    layer3Enabled: true,
    layer3Type: 'nebula',
    layer3Source: 'sphere',
    layer3Count: 9000,
    layer3FlowAmplitude: 40,
    layer3Life: 108,
    layer3LifeSpread: 0.5,
    layer3Burst: 0.25,
    layer3Streak: 0.55,
    layer3SpriteMode: 'soft',
    screenPersistenceIntensity: 0.14,
    ambientCount: 4000,
  }),
  createStarterPreset('starter-pinwheel-runes', 'Pinwheel Runes', {
    cameraControlMode: 'hybrid',
    renderQuality: 'balanced',
    cameraImpulseStrength: 0.1,
    cameraImpulseSpeed: 0.72,
    cameraImpulseDrift: 0.14,
    cameraBurstBoost: 0.3,
    screenBurstDrive: 0.28,
    screenBurstNoiseBoost: 0.2,
    screenBurstFlashBoost: 0.22,
    particleColor: 'black',
    backgroundColor: 'white',
    contrast: 1.38,
    layer1Count: 10000,
    layer2Type: 'pinwheel',
    layer2Source: 'ring',
    layer2Count: 23000,
    layer2FlowAmplitude: 58,
    layer2Life: 56,
    layer2LifeSpread: 0.2,
    layer2LifeSizeBoost: 0.28,
    layer2LifeSizeTaper: 0.18,
    layer2Burst: 0.48,
    layer2BurstMode: 'sweep',
    layer2BurstWaveform: 'heartbeat',
    layer2BurstSweepSpeed: 1.5,
    layer2BurstSweepTilt: 0.58,
    layer2EmitterOrbitSpeed: 1.1,
    layer2EmitterOrbitRadius: 28,
    layer2EmitterPulseAmount: 0.1,
    layer2TrailDrag: 0.46,
    layer2TrailTurbulence: 0.22,
    layer2TrailDrift: 0.41,
    layer2VelocityGlow: 0.58,
    layer2VelocityAlpha: 0.24,
    layer2FlickerAmount: 0.26,
    layer2FlickerSpeed: 2.25,
    layer2LineVelocityGlow: 0.34,
    layer2LineVelocityAlpha: 0.18,
    layer2LineBurstPulse: 0.38,
    layer2LineShimmer: 0.22,
    layer2LineFlickerSpeed: 1.9,
    layer2Streak: 0.8,
    layer2SpriteMode: 'ring',
    layer3Enabled: true,
    layer3Type: 'runes',
    layer3Source: 'cube',
    layer3Count: 8000,
    layer3FlowAmplitude: 30,
    layer3Life: 78,
    layer3LifeSpread: 0.18,
    layer3Burst: 0.18,
    layer3Streak: 0.32,
    layer3SpriteMode: 'spark',
  }),
  createStarterPreset('starter-monolith-nova', 'Monolith Nova', {
    cameraControlMode: 'manual',
    renderQuality: 'cinematic',
    cameraImpulseStrength: 0.18,
    cameraImpulseSpeed: 1.2,
    cameraImpulseDrift: 0.26,
    cameraBurstBoost: 0.62,
    screenBurstDrive: 0.48,
    screenBurstNoiseBoost: 0.24,
    screenBurstFlashBoost: 0.62,
    viewMode: 'orthographic',
    layer1Count: 9000,
    layer2Type: 'monolith',
    layer2Source: 'grid',
    layer2Count: 22000,
    layer2FlowAmplitude: 42,
    layer2ConnectionEnabled: true,
    layer2ConnectionDistance: 24,
    layer2ConnectionOpacity: 0.14,
    layer2LineVelocityGlow: 0.28,
    layer2LineVelocityAlpha: 0.18,
    layer2LineBurstPulse: 0.22,
    layer2Life: 96,
    layer2LifeSpread: 0.12,
    layer2LifeSizeBoost: 0.18,
    layer2LifeSizeTaper: 0.1,
    layer2Burst: 0.12,
    layer2BurstMode: 'cone',
    layer2BurstWaveform: 'single',
    layer2BurstConeWidth: 0.18,
    layer2EmitterOrbitSpeed: 0.35,
    layer2EmitterPulseAmount: 0.08,
    layer2Streak: 0.4,
    layer2SpriteMode: 'ring',
    layer3Enabled: true,
    layer3Type: 'nova',
    layer3Source: 'sphere',
    layer3Count: 7000,
    layer3FlowAmplitude: 36,
    layer3Life: 52,
    layer3LifeSpread: 0.22,
    layer3LifeSizeBoost: 0.74,
    layer3LifeSizeTaper: 0.42,
    layer3Burst: 0.82,
    layer3BurstMode: 'radial',
    layer3BurstWaveform: 'heartbeat',
    layer3BurstSweepSpeed: 1.8,
    layer3BurstConeWidth: 0.12,
    layer3EmitterOrbitSpeed: 1.9,
    layer3EmitterOrbitRadius: 18,
    layer3EmitterPulseAmount: 0.12,
    layer3TrailDrag: 0.66,
    layer3TrailTurbulence: 0.34,
    layer3TrailDrift: 0.28,
    layer3VelocityGlow: 1.1,
    layer3VelocityAlpha: 0.6,
    layer3FlickerAmount: 0.42,
    layer3FlickerSpeed: 3.8,
    layer3Streak: 1.35,
    layer3SpriteMode: 'spark',
    layer3SparkEnabled: true,
    layer3SparkCount: 7500,
    layer3SparkLife: 14,
    layer3SparkDiffusion: 2.9,
    layer3SparkBurst: 1.4,
    layer3LineVelocityGlow: 0.86,
    layer3LineVelocityAlpha: 0.48,
    layer3LineBurstPulse: 0.94,
    layer3LineShimmer: 0.4,
    layer3LineFlickerSpeed: 3.1,
    screenSweepIntensity: 0.15,
  }),
];

export const STARTER_PRESET_SEQUENCE: PresetSequenceItem[] = [
  {
    id: 'starter-sequence-simple-clean',
    presetId: 'starter-simple-clean',
    label: 'Starter Clean',
    holdSeconds: 2.6,
    transitionSeconds: 0.9,
    transitionEasing: 'ease-in-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-fluid-curl',
    presetId: 'starter-fluid-curl',
    label: 'Fluid Curl Field',
    holdSeconds: 3.2,
    transitionSeconds: 1.3,
    transitionEasing: 'ease-in-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-chaos-lorenz',
    presetId: 'starter-chaos-lorenz',
    label: 'Chaos Lorenz Bloom',
    holdSeconds: 3.4,
    transitionSeconds: 1.6,
    transitionEasing: 'ease-in',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1.1,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-orbital-epicycle',
    presetId: 'starter-orbital-epicycle',
    label: 'Orbital Epicycle',
    holdSeconds: 3,
    transitionSeconds: 1.2,
    transitionEasing: 'ease-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-geometry-lattice',
    presetId: 'starter-geometry-lattice',
    label: 'Geometry Lattice',
    holdSeconds: 2.8,
    transitionSeconds: 1.15,
    transitionEasing: 'linear',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 0.9,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-toroidal-gyre',
    presetId: 'starter-toroidal-gyre',
    label: 'Toroidal Gyre',
    holdSeconds: 3.1,
    transitionSeconds: 1.25,
    transitionEasing: 'ease-in-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1.05,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-symmetry-lissajous',
    presetId: 'starter-symmetry-lissajous',
    label: 'Symmetry Lissajous',
    holdSeconds: 2.8,
    transitionSeconds: 1.1,
    transitionEasing: 'ease-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 0.95,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-aizawa-ink',
    presetId: 'starter-aizawa-ink',
    label: 'Aizawa Ink Spiral',
    holdSeconds: 3.3,
    transitionSeconds: 1.35,
    transitionEasing: 'ease-in',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-fractal-ridged',
    presetId: 'starter-fractal-ridged',
    label: 'Fractal Ridged Storm',
    holdSeconds: 3.5,
    transitionSeconds: 1.5,
    transitionEasing: 'ease-in-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1.1,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-kaleido-prism',
    presetId: 'starter-kaleido-prism',
    label: 'Kaleido Prism',
    holdSeconds: 2.9,
    transitionSeconds: 1.1,
    transitionEasing: 'ease-in-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 0.95,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-pulse-shell',
    presetId: 'starter-pulse-shell',
    label: 'Pulse Shell',
    holdSeconds: 3,
    transitionSeconds: 1.2,
    transitionEasing: 'ease-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-mandala-bloom',
    presetId: 'starter-mandala-bloom',
    label: 'Mandala Bloom',
    holdSeconds: 3,
    transitionSeconds: 1.2,
    transitionEasing: 'ease-in-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-spokes-breath',
    presetId: 'starter-spokes-breath',
    label: 'Spokes Breath',
    holdSeconds: 2.9,
    transitionSeconds: 1.1,
    transitionEasing: 'ease-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 0.95,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-knot-flare',
    presetId: 'starter-knot-flare',
    label: 'Torus Knot Flare',
    holdSeconds: 3.1,
    transitionSeconds: 1.2,
    transitionEasing: 'ease-in-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-caustic-nebula',
    presetId: 'starter-caustic-nebula',
    label: 'Caustic Nebula',
    holdSeconds: 3.2,
    transitionSeconds: 1.3,
    transitionEasing: 'ease-in-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1.05,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-pinwheel-runes',
    presetId: 'starter-pinwheel-runes',
    label: 'Pinwheel Runes',
    holdSeconds: 2.9,
    transitionSeconds: 1.15,
    transitionEasing: 'ease-out',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 0.95,
    keyframeConfig: null,
  },
  {
    id: 'starter-sequence-monolith-nova',
    presetId: 'starter-monolith-nova',
    label: 'Monolith Nova',
    holdSeconds: 3.1,
    transitionSeconds: 1.25,
    transitionEasing: 'ease-in',
    screenSequenceDriveMode: 'inherit',
    screenSequenceDriveStrengthMode: 'inherit',
    screenSequenceDriveStrengthOverride: null,
    screenSequenceDriveMultiplier: 1,
    keyframeConfig: null,
  },
];

export const STARTER_PRESET_LIBRARY: PresetLibraryData = {
  version: 1,
  exportedAt: STARTER_TIMESTAMP,
  currentConfig: STARTER_PRESETS[0]?.config ?? normalizeConfig(DEFAULT_CONFIG),
  activePresetId: STARTER_PRESETS[0]?.id ?? null,
  presetBlendDuration: 1.4,
  sequenceLoopEnabled: true,
  presets: STARTER_PRESETS,
  presetSequence: STARTER_PRESET_SEQUENCE,
};
